In [1]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data

In [2]:
nnfs.init()

In [8]:
class Layer_Dense():
    def __init__(self,n_input,n_neurons):
        self.weights = 0.01*np.random.randn(n_input, n_neurons)
        self.biases = np.zeros((1,n_neurons))
        
    def forward(self,inputs):
        self.output = np.dot(inputs,self.weights) + self.biases
        
x,y = spiral_data(samples = 100, classes=3)

dense1 = Layer_Dense(2,3)

dense1.forward(x)
print(dense1.output[:10])

[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [ 1.2344425e-04 -4.2612613e-05  8.7741073e-06]
 [ 2.5981691e-04 -1.5019374e-04  2.1353657e-05]
 [ 4.0532288e-04 -3.3390927e-04  3.8064085e-05]
 [ 5.5259373e-04 -6.4534455e-04  6.0963972e-05]
 [ 5.5582222e-04  2.4813102e-05  2.9169312e-05]
 [ 3.7192379e-04  7.8886398e-04 -1.7323548e-05]
 [ 5.8084552e-04  5.9657131e-04  3.2591595e-06]
 [ 1.0184456e-03 -4.8815410e-04  7.8904784e-05]
 [-2.3062548e-04  2.2947381e-03 -1.2206852e-04]]
