In [1]:
import numpy as np
import nnfs

In [2]:
nnfs.init()

In [4]:
print(np.random.randn(2,5))

[[ 1.7640524   0.4001572   0.978738    2.2408931   1.867558  ]
 [-0.9772779   0.95008844 -0.1513572  -0.10321885  0.41059852]]


In [7]:
print(np.zeros((2,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
n_input = 2
n_neuron = 4

In [11]:
weights = 0.01*np.random.randn(n_input, n_neuron)
biases = np.zeros ((1,n_neuron))

In [19]:
print(weights)

[[ 0.00144044  0.01454273  0.00761038  0.00121675]
 [ 0.00443863  0.00333674  0.01494079 -0.00205158]]


In [20]:
print(biases)

[[0. 0. 0. 0.]]
